[alias]
br = 'build --release'
rr = 'run --release'
f = 'fmt'

[registries.crates-io]
protocol = "sparse"

# Set the settings for build scripts and proc-macros.
[profile.release.build-override]
opt-level = 0
[profile.bench.build-override]
opt-level = 0

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    # Use `diff <(rustc --print cfg) <(rustc --print cfg -C target-cpu=<cpu name>)`
    # to know what new target features are enabled
    "-C", "target-cpu=sandybridge",
]
linker = "clang"
