[alias]
br = 'build --release'
rr = 'run --release'
f = 'fmt'
lto = 'build --profile=lto'

[registries.crates-io]
protocol = "sparse"

[net]
git-fetch-with-cli = true

[profile.lto]
inherits = "release"
lto = "thin"
codegen-units = 1
strip = "debuginfo"
# FIXME: abort doesn't work in `cargo-expand`. As it unwraps
# somewhere in `proc-macro2` crate.
#panic = 'abort'

# Set the settings for build scripts and proc-macros.
[profile.dev.package."*"]
debug = "limited"
[profile.dev.build-override]
debug = false
[profile.release.build-override]
opt-level = 0
[profile.bench.build-override]
opt-level = 0

[target.x86_64-unknown-linux-gnu]
# linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    # Use `diff <(rustc --print cfg) <(rustc --print cfg -C target-cpu=<cpu name>)`
    # to know what new target features are enabled
    "-C", "target-cpu=sandybridge",
]
